[FIO extras] fit: verify: abort if signature not found and strict
Prefer aborting the fit verification process when a signature node is
not found by U-Boot and FIT SIGNATURE STRICT is enabled. This is a way
to always force a proper signature verification via sig verify.

Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>

[FIO toup-squash] spl: minor fixes for FIT_SIGNATURE_STRICT mode

This fixes a possible ambiguous 'else' [2] and using undeclared
function hang() [1].

[1]
common/spl/spl_fit.c: In function ‘spl_load_fit_image’:
common/spl/spl_fit.c:335:5: warning: implicit declaration of function ‘hang’ [-Wimplicit-function-declaration]
  335 |     hang();
      |     ^~~~
---------------------------------------------------------------------
[2]
common/spl/spl_fit.c:332:6: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wdangling-else]
  332 |   if (!fit_image_verify_with_data(fit, node, src, length))
      |      ^
---------------------------------------------------------------------
Fixes: dd9336eccb ("[FIO fromlist] spl: Add CONFIG_SPL_FIT_SIGNATURE_STRICT")
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>

[FIO toup-squash] spl: use spl_simple_fit_parse for STRICT validation

FIT image is already parsed and verified by the spl_simple_fit_parse
function, so instead of searching for the default config node entry and
validating its signature, just use the return code from the fit parser
and hang in case of errors.

Fixes: dd9336eccb ("[FIO fromlist] spl: Add CONFIG_SPL_FIT_SIGNATURE_STRICT")
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>
Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>